---
 - name: add ssh key for sysadmin
   tags: always
   authorized_key:
      user: sysadmin
      key: 
 - name: generate sshd_config file from template
   tags: ssh
   template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
   notify: restart_sshd

 - name: Change SELinux mode to permissive
   become: yes
   selinux:
    policy: targeted
    state: permissive
