---

- hosts: file_servers
  gather_facts: True

  become: true
  

  tasks:

  - name: updating password for sysadmin
    user: name=sysadmin update_password=always password=$6$RICMF4uJdwwZkEmj$5sFh0JbSV3i.1rqGM.lfzhML9yCk6WQl04n65WQHA1GRVnjvdGer/hYxblul2B4l86VAEqFI71
